### ISSUE TITLE
[suggestion]: Dashboard filter for trained unassigned

### ISSUE THREAD

**Issue by U-B-Glade** [LSS-Manager/lss-manager-v3#1106]
I suggest a Dashboard "Sheet" for trained but unassigned Personal at all Stations. So I can pick that Peoble, they are trained but not assigned to a vehicle, and put them to an other Station.

**Comment by jxn-30** [comment]
LSS-Manager V3 is discontinued, but [V4](https://github.com/LSS-Manager/LSSM-V.4) isn't.
However, an overview of staff will probably never be available because there is no API (due to huge amount of data) & it would cost too many server requests to collect the information manually via a script.
If there ever will be a possibility to get a nice overview of staff, we will implement tools therefore, but currently not.

Closing here, because V3 is discontinued & currently not possible unfortunately.
