### ISSUE TITLE
[Idea] Update Notifications

### ISSUE THREAD

**Issue by spc0806** [LSS-Manager/lss-manager-v3#157]
I think it would be amazing if there was a way that a notification could be triggered on the website by the dev team if there is a new beta version available.

**Comment by lostdesign** [comment]
Actually @jalibu just realized that yesterday. Since the dev team has grown so fast we decided to change the way we work. One of the things was adding a *realease note* plugin, which tells the user, what has changed and what's new. 

It's still under development, but should be released soon. For now i'll mark this as closed.

**Comment by lostdesign** [comment]
See #156
